# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Service definition for the Python TrippleEffect agent sidecar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeAgent = channel.unary_unary(
                '/agent.AgentService/InitializeAgent',
                request_serializer=agent__pb2.InitializeRequest.SerializeToString,
                response_deserializer=agent__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_stream(
                '/agent.AgentService/SendMessage',
                request_serializer=agent__pb2.MessageRequest.SerializeToString,
                response_deserializer=agent__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetAgentState = channel.unary_unary(
                '/agent.AgentService/GetAgentState',
                request_serializer=agent__pb2.StateRequest.SerializeToString,
                response_deserializer=agent__pb2.StateResponse.FromString,
                _registered_method=True)
        self.TransitionState = channel.unary_unary(
                '/agent.AgentService/TransitionState',
                request_serializer=agent__pb2.TransitionRequest.SerializeToString,
                response_deserializer=agent__pb2.TransitionResponse.FromString,
                _registered_method=True)
        self.TerminateAgent = channel.unary_unary(
                '/agent.AgentService/TerminateAgent',
                request_serializer=agent__pb2.TerminateRequest.SerializeToString,
                response_deserializer=agent__pb2.TerminateResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Service definition for the Python TrippleEffect agent sidecar
    """

    def InitializeAgent(self, request, context):
        """Initialize a new agent or resume an existing one
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message to an agent and get its response stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentState(self, request, context):
        """Get the current state of an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransitionState(self, request, context):
        """Force a state transition for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateAgent(self, request, context):
        """Terminate an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeAgent,
                    request_deserializer=agent__pb2.InitializeRequest.FromString,
                    response_serializer=agent__pb2.InitializeResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=agent__pb2.MessageRequest.FromString,
                    response_serializer=agent__pb2.MessageResponse.SerializeToString,
            ),
            'GetAgentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentState,
                    request_deserializer=agent__pb2.StateRequest.FromString,
                    response_serializer=agent__pb2.StateResponse.SerializeToString,
            ),
            'TransitionState': grpc.unary_unary_rpc_method_handler(
                    servicer.TransitionState,
                    request_deserializer=agent__pb2.TransitionRequest.FromString,
                    response_serializer=agent__pb2.TransitionResponse.SerializeToString,
            ),
            'TerminateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateAgent,
                    request_deserializer=agent__pb2.TerminateRequest.FromString,
                    response_serializer=agent__pb2.TerminateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Service definition for the Python TrippleEffect agent sidecar
    """

    @staticmethod
    def InitializeAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/InitializeAgent',
            agent__pb2.InitializeRequest.SerializeToString,
            agent__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentService/SendMessage',
            agent__pb2.MessageRequest.SerializeToString,
            agent__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GetAgentState',
            agent__pb2.StateRequest.SerializeToString,
            agent__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransitionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/TransitionState',
            agent__pb2.TransitionRequest.SerializeToString,
            agent__pb2.TransitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/TerminateAgent',
            agent__pb2.TerminateRequest.SerializeToString,
            agent__pb2.TerminateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
